### ISSUE TITLE
Output of Code_Aster fails

### ISSUE THREAD

**Issue by micheltakken** [precice/code_aster-adapter#11]
If the output for Code_Aster is enabled, the coupling will crash because Code_Aster is writing a result file. The Code_Aster output should be improved, such that it doesn't interfere with the coupling process.

**Comment by micheltakken** [comment]
Posted a [topic](https://code-aster.org/forum2/viewtopic.php?pid=60943#p60943) on the Code_Aster forum regarding this problem.

**Comment by benoitpaillard** [comment]
Hi, could you provide a minimal code_aster case, so that I can run into the issue myself ?

Good thing you posted on aster forum, it's not as active as it used to be but I'll still follow up on there as well.

**Comment by micheltakken** [comment]
Open it in Salome_Meca 2018 or newer. Salome_Meca 2017 uses an older version of MED.
Apart from that, adapter.comm was adapted in lines 136 to 140. A counter was added to the unit number for each file that was saved. This solution was taken from 
the tutorial "forma01c" provided with Code_Aster.
