### ISSUE TITLE
AssertionError on set_mesh_vertices

### ISSUE THREAD

**Issue by MakisH** [precice/code_aster-adapter#21]
I am trying to rerun our code_aster case, and I am getting a cryptic `AssertionError` from `cyprecice.pyx`, line 533 from `set_mesh_vertices` (bindings v2.2.0.1). Is this again related to wrong type? Is this the same known issue for missing an error message (https://github.com/precice/python-bindings/issues/74)? I am just wondering because this code was working around a year ago.

```
!  in configure                                                                     !
   !     self.setVertices()                                                            !
   !    File "/home/vagrant/code_aster/14.6/lib/aster/Execution/adapter.py", line 190, !
   !  in setVertices                                                                   !
   !     self.preciceNodeIndices =                                                     !
   ! self.precice.set_mesh_vertices(self.preciceNodesMeshID,  self.nodeCoordinates)    !
   !    File "cyprecice/cyprecice.pyx", line 533, in                                   !
   ! cyprecice.Interface.set_mesh_vertices                                             !
   !  AssertionError                                                                   !
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

This is the line that triggers it:

https://github.com/precice/code_aster-adapter/blob/master/cht/adapter.py#L34

I am using code_aster 14.6, even though previously we were using 14.4, but this should only be related to the adapter and the bindings. @BenjaminRodenberg @IshaanDesai is there a nice way to convert the given data type to the expected one?

**Comment by IshaanDesai** [comment]
The assertion hit in this is this one:

https://github.com/precice/python-bindings/blob/d5383d6e4be2424aacbb0d24ab1e9c2a8212713b/cyprecice/cyprecice.pyx#L533

which means that the variable `self.nodeCoordinates` is not following the shape rules:
```
        positions : array_like
            The coordinates of the vertices in a numpy array [N x D] where
            N = number of vertices and D = dimensions of geometry.
```
Checking the shape of `self.nodeCoorindates` would be helpful. https://github.com/precice/python-bindings/pull/9 will provide a better error message here, as it is clear that the user gets no information from the bindings on what the possible problem is.

**Comment by MakisH** [comment]
FYI, this is where the `MESH` is defined:

https://github.com/precice/tutorials/blob/master/CHT/flow-over-plate/buoyantSimpleFoam-aster/Solid/def.comm#L3-L11

```python
MESH = LIRE_MAILLAGE(UNITE=20, FORMAT='MED',);

MESH = DEFI_GROUP(
	reuse=MESH,
	MAILLAGE=MESH,
	CREA_GROUP_NO=_F(
		TOUT_GROUP_MA='OUI',
		),
);
```

I guess we need to start digging to understand what is happening.

**Comment by MakisH** [comment]
As @uekerman told me, we can actually use one of:
- https://numpy.org/doc/stable/reference/generated/numpy.ravel.html
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html

**Comment by IshaanDesai** [comment]
@MakisH can you please try to re run the case with [this branch](https://github.com/precice/python-bindings/tree/improvedErrorMessages) of the python-bindings? You should then receive a more meaningful assertion message.

**Comment by IshaanDesai** [comment]
Closed in https://github.com/precice/code_aster-adapter/pull/22
